#!/bin/sh

if [ -z "$1" ]; then
    echo "Need path to project root"
    exit 1
fi

if [ -z "$2" ]; then
    echo "Need path to virtual environment to install virtualenv"
    exit 1
fi

if [ `uname` == "Darwin" ]; then
    export ARCHFLAGS="-arch i386 -arch x86_64"
fi
which ccache > /dev/null 2>&1
if [ $? == 0 ]; then
    export CC='ccache gcc'
fi

. $2/bin/activate

vendor=$1/vendors
cd $vendor
easy_install $vendor/amqplib-1.0.2.tgz
easy_install $vendor/virtualenv-1.6.4.tar.gz
easy_install $vendor/ipython-0.10.1.tar.gz

easy_install $vendor/unittest2-0.5.1.tar.gz
easy_install $vendor/logilab-common-0.53.0.tar.gz
easy_install $vendor/logilab-astng-0.21.0.tar.gz
easy_install $vendor/pylint-0.22.0.tar.gz

easy_install $vendor/coverage-3.4.tar.gz
easy_install $vendor/unittest-xml-reporting-1.0.3.tar.gz

easy_install $vendor/pyrepl-0.8.2.tar.gz
easy_install $vendor/fancycompleter-0.2.tar.gz
easy_install $vendor/Pygments-1.3.1.tar.gz
easy_install $vendor/wmctrl-0.1.tar.gz
easy_install $vendor/pdbpp-0.6.tar.gz

easy_install $vendor/docutils-0.7.tar.gz
easy_install $vendor/pysmell-0.7.3.zip

easy_install $vendor/pymongo-1.11.tar.gz
easy_install $vendor/ftputil-2.6.tar.gz
easy_install $vendor/setproctitle-1.1.3.tar.gz
easy_install $vendor/httplib2-0.7.2.tar.gz
easy_install $vendor/python_rest_client2.tar.gz
easy_install $vendor/Jinja2-2.6.tar.gz
easy_install $vendor/Werkzeug-0.8.1.tar.gz
easy_install $vendor/psutil-0.4.0.tar.gz
